### ISSUE TITLE
Error de ortografia

### ISSUE THREAD

**Issue by Rootbo3** [dr-nefardio3058/Tools#1]
HTML - blogs: error de ortografia en la linea 18

**Comment by dr-nefardio3058** [comment]
a bueno muchas gracias por reportarlo! puedes hacer una pull request para arreglarlo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

@Rootbo3 

tendrias que hacer esto

- [ ] a
- [ ] b
- [ ] c

**Comment by Rootbo3** [comment]
Este issue fue resuelto en la #2
